// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnmq1IGxOn5rZOnoh2B06vrqseGPXbXc',
    appId: '1:74808558861:web:c82921d6e8d284e66b5c44',
    messagingSenderId: '74808558861',
    projectId: 'ppb-final-project-e129d',
    authDomain: 'ppb-final-project-e129d.firebaseapp.com',
    storageBucket: 'ppb-final-project-e129d.firebasestorage.app',
    measurementId: 'G-767T8RF6S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTRF4bepq0tdOjKlyqOAzs55CXBhbdZE',
    appId: '1:74808558861:android:9aea321b8e23c36d6b5c44',
    messagingSenderId: '74808558861',
    projectId: 'ppb-final-project-e129d',
    storageBucket: 'ppb-final-project-e129d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn-DrQ-JbuFkmCQ053pT6d2--FiuEr7ng',
    appId: '1:74808558861:ios:2ea1994fdcd7fc756b5c44',
    messagingSenderId: '74808558861',
    projectId: 'ppb-final-project-e129d',
    storageBucket: 'ppb-final-project-e129d.firebasestorage.app',
    iosBundleId: 'com.example.ppbFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn-DrQ-JbuFkmCQ053pT6d2--FiuEr7ng',
    appId: '1:74808558861:ios:2ea1994fdcd7fc756b5c44',
    messagingSenderId: '74808558861',
    projectId: 'ppb-final-project-e129d',
    storageBucket: 'ppb-final-project-e129d.firebasestorage.app',
    iosBundleId: 'com.example.ppbFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwnmq1IGxOn5rZOnoh2B06vrqseGPXbXc',
    appId: '1:74808558861:web:1886d0412a110c9f6b5c44',
    messagingSenderId: '74808558861',
    projectId: 'ppb-final-project-e129d',
    authDomain: 'ppb-final-project-e129d.firebaseapp.com',
    storageBucket: 'ppb-final-project-e129d.firebasestorage.app',
    measurementId: 'G-WPC7KNGRHN',
  );
}
